# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-14 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffregistration', '0004_paymentdetails'),
        ('staffrecruit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr1', models.CharField(max_length=255)),
                ('addr2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=63)),
                ('pin', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Adminpos',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('resp_held', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('yearofpassing', models.CharField(max_length=255)),
                ('cgpa', models.CharField(max_length=255)),
                ('classdiv', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('org', models.CharField(max_length=255)),
                ('doj', models.CharField(max_length=255)),
                ('dol', models.CharField(max_length=255)),
                ('pay', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Extracurr',
            fields=[
                ('ex_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('l_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('read', models.BooleanField(default=False)),
                ('write', models.BooleanField(default=False)),
                ('speak', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=255)),
                ('father_occ', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('mother_occ', models.CharField(blank=True, max_length=255)),
                ('nation', models.CharField(max_length=255)),
                ('pob', models.CharField(max_length=255)),
                ('dob', models.CharField(default='NA', max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('maritalstatus', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=10)),
                ('obccreamy', models.BooleanField(default=False)),
                ('pwd', models.CharField(default='no', max_length=10)),
                ('adminpos', models.ManyToManyField(to='staffrecruit.Adminpos')),
            ],
        ),
        migrations.AddField(
            model_name='staffapp',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='staffregistration.Post'),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='app_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffrecruit.StaffApp'),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='correspond_addr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspond_addr', to='staffrecruit.Address'),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='educationdet',
            field=models.ManyToManyField(to='staffrecruit.Education'),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='exprdet',
            field=models.ManyToManyField(to='staffrecruit.Experience'),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='extracurr',
            field=models.ManyToManyField(to='staffrecruit.Extracurr'),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='languages',
            field=models.ManyToManyField(to='staffrecruit.Language'),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='memberships',
            field=models.ManyToManyField(to='staffrecruit.Membership'),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='permanent_addr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_addr', to='staffrecruit.Address'),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='refrences',
            field=models.ManyToManyField(to='staffrecruit.Reference'),
        ),
    ]
