# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-14 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffrecruit', '0004_auto_20180914_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffuser',
            name='proof',
        ),
        migrations.DeleteModel(
            name='Proof',
        ),
    ]
