# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-14 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import staffrecruit.models


class Migration(migrations.Migration):

    dependencies = [
        ('staffrecruit', '0005_auto_20180914_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appID', models.CharField(max_length=255)),
                ('prooffile', models.FileField(null=True, upload_to=staffrecruit.models.get_proof_path)),
            ],
        ),
        migrations.AddField(
            model_name='staffuser',
            name='proof',
            field=models.ManyToManyField(to='staffrecruit.Proof'),
        ),
    ]
