# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-14 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffrecruit', '0006_auto_20180914_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffuser',
            name='exprdet',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
