# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-14 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffrecruit', '0007_auto_20180914_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('org', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('doj', models.CharField(max_length=255)),
                ('dol', models.CharField(max_length=255)),
                ('pay', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='staffuser',
            name='exprdet',
            field=models.ManyToManyField(to='staffrecruit.Experience'),
        ),
    ]
