# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-13 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffregistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='postApplied',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffregistration.Post'),
        ),
    ]
