# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-13 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffregistration', '0002_auto_20180913_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='appCount',
            field=models.IntegerField(default=0),
        ),
    ]
