# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-13 07:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import staffregistration.models


class Migration(migrations.Migration):

    dependencies = [
        ('staffregistration', '0003_post_appcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appID', models.CharField(max_length=20)),
                ('bankName', models.CharField(blank=True, max_length=100, null=True)),
                ('transID', models.CharField(max_length=50)),
                ('accountNum', models.CharField(max_length=30)),
                ('payDate', models.CharField(blank=True, max_length=20, null=True)),
                ('payType', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.CharField(blank=True, max_length=10, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to=staffregistration.models.get_pay_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
        ),
    ]
