# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-06 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='applicationID',
            field=models.CharField(max_length=20),
        ),
    ]
