# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-29 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20180906_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='transID',
            field=models.CharField(max_length=512),
        ),
    ]
