# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-30 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_merge_20181030_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='transID',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
