# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-05 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr1', models.CharField(max_length=255)),
                ('addr2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=63)),
                ('pin', models.CharField(max_length=31)),
            ],
        ),
        migrations.AlterField(
            model_name='facuser',
            name='correspond_addr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspond_addr', to='recruit.Address'),
        ),
        migrations.AlterField(
            model_name='facuser',
            name='permanent_addr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_addr', to='recruit.Address'),
        ),
    ]
