# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-06 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_auto_20180906_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdata',
            name='app_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
