# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-25 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0004_auto_20181025_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='marks',
            field=models.CharField(max_length=3),
        ),
    ]
