# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-28 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0005_auto_20181025_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdata',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
