# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-30 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0006_appdata_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appdata',
            name='payment',
        ),
    ]
